kind: Secret
apiVersion: v1
metadata:
  name: object1-secret-0
  namespace: ibm-spectrum-fusion-ns
  labels:
    dp.isf.ibm.com/ownedBy: fbsl
    dp.isf.ibm.com/provider-name: isf-backup-restore
data:
  access-key-id: bWluaW9hZG1pbg==
  secret-access-key: bWluaW9hZG1pbg==
type: Opaque
