kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    app.openshift.io/vcs-ref: ''
    app.openshift.io/vcs-uri: 'https://github.com/jblumert/filebrowser'
    openshift.io/generated-by: OpenShiftWebConsole
  name: filebrowser
  namespace: filebrowser
  labels:
    app: filebrowser
    app.kubernetes.io/component: filebrowser
    app.kubernetes.io/instance: filebrowser
    app.kubernetes.io/name: filebrowser
    app.kubernetes.io/part-of: filebrowser-app
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'filebrowser:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Dockerfile
  postCommit: {}
  source:
    type: Git
    git:
      uri: 'https://github.com/jblumert/filebrowser'
    contextDir: /
  triggers:
    - type: Generic
      generic:
        secretReference:
          name: filebrowser-generic-webhook-secret
    - type: GitHub
      github:
        secretReference:
          name: filebrowser-github-webhook-secret
    - type: ConfigChange
  runPolicy: Serial
