# .bashrc

# Source global definitions
if [ -f /etc/bashrc ]; then
	. /etc/bashrc
fi

# User specific environment
if ! [[ "$PATH" =~ "$HOME/.local/bin:$HOME/bin:" ]]
then
    PATH="$HOME/.local/bin:$HOME/bin:$PATH"
fi
export PATH

# Uncomment the following line if you don't like systemctl's auto-paging feature:
# export SYSTEMD_PAGER=

# User specific aliases and functions
export KUBECONFIG=/tmp/ocp/cluster/auth/kubeconfig
#
#export OCP_USERNAME=kubeadmin
#export OCP_PASSWORD=6dZSj-J6KrW-tJUAr-9yAQj
#export OCP_URL=https://api.660cae5f3abee4001ecaab91.cloud.techzone.ibm.com:6443
. ~/cpd_var.sh
