apiVersion: prereq.isf.ibm.com/v1
kind: SpectrumFusion
metadata:
  name: spectrumfusion
  namespace: ibm-spectrum-fusion-ns
spec:
  DataProtection:
    Enable: false
  GlobalDataPlatform:
    Enable: false
  OpenShiftDataFoundation:
    AutoUpgrade: false
    Enable: false
  configuration:
    services: {}
  license:
    accept: true
