---
apiVersion: v1
kind: Namespace
metadata:
  name: ibm-spectrum-fusion-ns
spec:
---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: ibm-spectrum-fusion-operator-group
  namespace: ibm-spectrum-fusion-ns
spec:
  targetNamespaces:
  - ibm-spectrum-fusion-ns
  upgradeStrategy: Default
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: isf-operator
  namespace: ibm-spectrum-fusion-ns
spec:
  channel: v2.0
  installPlanApproval: Automatic
  name: isf-operator
  source: ibm-operator-catalog
  sourceNamespace: openshift-marketplace
  startingCSV: isf-operator.v2.7.2